version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  api:
    image: node
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: todos
      PORT: 4000
    volumes:
      - ./todo-back/:/app/
    working_dir: /app/
    command: npm run dev
    ports:
      - 4000:4000
    depends_on:
      - mongo

  front:
    image: node
    environment:
      REACT_APP_HOST: localhost
      REACT_APP_PORT: 4000
    stdin_open: true
    volumes:
      - ./todo-front/:/app/
    working_dir: /app/
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  mongodata:
